// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4919.Robot_2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4919.Robot_2015.Robot;

/**
 *
 */
public class  liftauto extends Command {
	private double time;
	private boolean goup;
	
    public liftauto(double time, boolean goup) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	this.time = time;
    	this.goup = goup;
        requires(Robot.manuallift);
    	
    }

    public liftauto() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	this.time = 0;
    	this.goup = true;
    	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.manuallift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setTimeout(time);
    	if (goup)
    		Robot.manuallift.liftup();
    	else
    		Robot.manuallift.liftdown();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.manuallift.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
